headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/seajelly/Documents/Xionsgroup/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "26.6.0"
ALLOW_INDEXING = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/groupe"
to = "/fr/groupe"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/about"
to = "/fr/groupe"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/marques"
to = "/fr/marques"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/brands"
to = "/fr/marques"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/engagements"
to = "/fr/engagements"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commitments"
to = "/fr/engagements"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/presse"
to = "/fr/presse"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/press"
to = "/fr/presse"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/carrieres"
to = "/fr/carrieres"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/careers"
to = "/fr/carrieres"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/contact"
to = "/fr/contact"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]